#!/bin/sh

set -eux

tag="${1-}"

if test -d container; then
    cd container
fi

if command -v podman; then
    podman="podman"
elif command -v flatpak-spawn; then
    podman="flatpak-spawn --host podman"
fi

if test -n "$tag"; then
    $podman build --tag "${tag}" .
    $podman push "${tag}"
else
    $podman build .
fi
