#!/bin/sh

if test -d container; then
    cd container
fi

cp -v ../src/cockpit-cloud-connector .
cp -v ../ephemeral-keys/server.{crt,key} .
cp -v ../ephemeral-keys/client.crt .
chmod a+r server.{crt,key} client.crt

if command -v podman; then
    podman="podman"
elif command -v flatpak-spawn; then
    podman="flatpak-spawn --host podman"
fi

$podman build "$@"
